### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#131]
Is there a license which allows:

- Free use
- Modifications
- Redistributions

Requires:

- Copyleft

Forbids:

- Any kind of commercial use

I couldn't find a popular license. CC BY-NC looks good but should not be used for software.

**Comment by dorthrithil** [comment]
@PeterGrabowitz Do you know about this stuff?

I changed from the previous open source license to all rights reserved until we find a good open license.

**Comment by PeterGrabowitz** [comment]
Will take a look.

**Comment by PeterGrabowitz** [comment]
Can´t really find anything fitting either. Maybe eventually have the club pay for 2 hours of an attorney...?

**Comment by BlobbyBob** [comment]
I do not have much legal expertise, but maybe the [Business Source License](https://en.wikipedia.org/wiki/Business_Source_License) could be worth a look. It is designed to forbid production environments, which means it forbids any commercial deployment, but also non-profit deployments. It is of course always possible to grant an interested party further rights under any custom terms.

**Comment by dorthrithil** [comment]
As I understand this licence, it is designed to transition to a fully open source license after a set period of time. So we still wouldn't be able to prevent arbitrary commercial use after this time. I think "All Rights Reserved" is pretty much the same then because here we can also grant rights and licences to parties that are interested.

**Comment by dorthrithil** [comment]
Still thinking about this tough.. probably my fears are irrational and just having a truly open source software is the cooler alternative.

**Comment by dorthrithil** [comment]
AGPL could be a nice candidate: https://fossa.com/blog/open-source-software-licenses-101-agpl-license/

In contrast to e.g. MIT, it ensures that any derivatives also have to be open source. This makes it very hard for companies to build a business model upon AGPL licensed software.

**Comment by PeterGrabowitz** [comment]
AGPL would likely bring the intended result. Probably though the long term result wouldn´t be different with "all rights reserved" with the dedicated intention of giving it out to anyone that actually wants to participate or use it in any noncommercial way. That covers all bases while not opening any flanks. Not sure if someone sees LC and then abandons any plans to participate/use due to it not being completely open source. On the other hand there might actually come scenarios where a commercial party grabs it if the license is too liberal. But, as said, AGPL looks good, too.

**Comment by dorthrithil** [comment]
How are your thought on Peters reply (the `Not sure if someone sees LC and then abandons any plans to participate/use due to it not being completely open source.` part) @BlobbyBob? You are the first and only contributor working with me on this project. If we wouldn't have started the licence discussion right away, would you have been just as happy to contribute to a project with proprietary licence owned by me?
It's kind of a trust issue I think. Of cause I can say LC will be free for anyone using it in my terms, but I can change that whenever I want. Of cause I won't do that, but a random contributor stumbling uopn this project doesn't know me. This would not be the case with AGPL.

**Comment by dorthrithil** [comment]
Added this to the 1.3.0 milestone, I finally have to make a decision here. :D

**Comment by BlobbyBob** [comment]
I've thought about it some more and I think I would prefer an open-source license by quite some margin. AGPL is probably a good fit for this.

> If we wouldn't have started the licence discussion right away, would you have been just as happy to contribute to a project with proprietary licence owned by me?

I'm not sure, it is always hard to judge in retrospective. At the beginning I was just hyped of having an interesting programming project again, but looking at it more objectively, it is also nice to have the guarantee that I and anyone I like will be able to use it. I might have done some minor contributions as I like Glees and the effort that has been put into the area, but I think it even was me who directly started the discussion of receiving an "unlimited" deployment license in exchange for contributing. It definitely feels better to invest lots of time into an OSS project instead of proprietary software, especially as the amount of contributions grow.

I also think commercial use by others will be fine and might even be beneficial for the project. With AGPL everyone would have the freedom to use it and customers could pay extra money to some third-party provider for a support contract or similar. But this third party would need to understand the project and at some point would likely either get feature requests or would be bothered by some bugs or inefficiency. (For example, did you know there currently is a "secret" unauthenticated endpoint that takes requests 55secs to finish on gleesbouldering and probably completely exhausts a core for that time :wink:). Then they would do some kind of contribution where the project and all of its non-commercial users would also profit from.  
But realistically, I do not expect any commercial interests in this project except for maybe hosters offering 1-click-web-app-deployments, which will them not earn much besides their normal operational costs.

Furthermore, I think as the project grows, it is pretty likely that more people are willing to contribute. Don't forget the first production instance is running for not even half a year! It takes some time until the right people stumble upon the project. They will probably feel the same as me about larger contributions.

And finally an OSS license is an easy way to keep the project alive in case you personally just lose interest in the project or you have the urgent need to disappear quickly because 42verticalCrags sends some headhunters after you or something similar :D

**Comment by PeterGrabowitz** [comment]
Sounds like a well grounded statement we could see as the final AGPL-trigger! ;)

**Comment by dorthrithil** [comment]
Hehe, good catch, the ranking endpoint definitely needs to be secured. I've thought about this and then forgot it.  
And I also think the decision is made here!

**Comment by dorthrithil** [comment]
We're OSS now! 🎉 
Will be completely official after 1.7.2 is merged in main
